# fail_fast: true
minimum_pre_commit_version: 4.5.0
exclude: |
  (?x)^(
      .*\{\{.*\}\}.*|     # Exclude any files with cookiecutter variables
      docs/site/.*|       # Exclude mkdocs compiled files
      docs/_build/.*|
      \.history/.*|       # Exclude history files
      .*cache.*/.*|       # Exclude cache directories
      .*venv.*/.*|        # Exclude virtual environment directories
      .direnv/.*|
      .yarn/.*|
      .ansible/.*|
      node_modules/.*|
      .npm/.*|
      .nuxt/.*|
      .netlify.*|
  )$
ci:
  # format compatible with commitlint
  autoupdate_commit_msg: "chore: pre-commit autoupdate"
  autoupdate_schedule: monthly
  autofix_commit_msg: |
    chore: auto fixes from pre-commit.com hooks
    for more information, see https://pre-commit.ci
  skip:
    # https://github.com/pre-commit-ci/issues/issues/55
    - pip-compile
    - pyright
    - schemas
  submodules: true
default_install_hook_types:
  - pre-commit # gitleak
    # make sure you include `prepare-commit-msg` in `default_install_hook_types`
    # prepare-commit-msg made by oco
    # - prepare-commit-msg
  - commit-msg
repos:
  # ---------------------------------------------------------------------------- #
  #                              ğŸ”„ Pre-Commit Hooks                             #
  # ---------------------------------------------------------------------------- #
  #- repo: meta
  #  hooks:
  #    - id: check-useless-excludes
  - repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.9.0
    hooks:
      - id: pre-commit-update

    # ---------------------------- ğŸ“ Filesystem Tools --------------------------- #
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        name: "ğŸ“ filesystem/âš™ï¸ exec Â· Remove trailing whitespace"
        args: [--markdown-linebreak-ext=md]
      - id: fix-byte-order-marker
        name: "ğŸ“ filesystem/âš™ï¸ exec Â· Verify byte order"
      - id: mixed-line-ending
        name: "ğŸ“ filesystem/âš™ï¸ exec Â· Verify mixed line ending"
        args: [--fix=lf]
      - id: end-of-file-fixer
        name: "ğŸ“ filesystem/âš™ï¸ exec Â· Verify end of file"
      - id: check-executables-have-shebangs
        name: "ğŸ“ filesystem/âš™ï¸ exec Â· Verify shebang preset"
        # exclude: >
        #   (?x)^(
        #       .mvn/|
        #       .venv|
        #       .direnv|
        #   )$
      - id: check-shebang-scripts-are-executable
        name: "ğŸ“ filesystem/âš™ï¸ exec Â· Verify script permissions"
      - id: check-symlinks
        name: "ğŸ“ filesystem/ğŸ”— symlink Â· Check symlink validity"
      - id: destroyed-symlinks
        name: "ğŸ“ filesystem/ğŸ”— symlink Â· Detect broken symlinks"
      - id: debug-statements
        name: "ğŸ“ filesystem/ğŸ“ debug Â· Check debug statements"
      - id: check-ast
        name: "ğŸ“ filesystem/ğŸ“ ast Â· Check ast"
      - id: check-builtin-literals
        name: "ğŸ“ filesystem/ğŸ“ literals Â· Check builtin literals"
      - id: check-case-conflict
        name: "ğŸ“ filesystem/ğŸ“ names Â· Check case sensitivity"
      - id: check-illegal-windows-names
        name: "ğŸ“ filesystem/ğŸ“ names Â· Validate Windows filenames"
      - id: check-docstring-first
        name: "ğŸ“ filesystem/ğŸ“ docstring Â· Validate docstring first"
      - id: name-tests-test
        name: "ğŸ“ filesystem/ğŸ“ names Â· Check tests names"

        # --------------------------- ğŸ” Code Quality Tools -------------------------- #
      - id: check-json
        name: "ğŸ“ filesystem/ğŸ“ json Â· Check json"
      - id: check-toml
        name: "ğŸ“ filesystem/ğŸ“œ toml - Check toml"
      - id: check-xml
        name: "ğŸ“ filesystem/ğŸ“œ xml - Check xml"
      - id: check-yaml
        name: "ğŸ“ filesystem/ğŸ“œ yaml - Check yaml"
        args: [--allow-multiple-documents]
      - id: sort-simple-yaml
        name: "ğŸ”€ sort/ğŸ“œ yaml - Sort yaml"
      - id: file-contents-sorter
        name: "ğŸ”€ sort/ğŸ“œ file Â· Sort contents"
      - id: requirements-txt-fixer
        name: "ğŸ”€ sort/ğŸ json Â· Sort requirements"
        # ------------------------------- ğŸŒ³ Git Tools ------------------------------- #
      - id: check-merge-conflict
        name: "ğŸŒ³ git Â· Detect conflict markers"
      - id: forbid-new-submodules
        name: "ğŸŒ³ git Â· Prevent submodule creation"
        # - id: no-commit-to-branch
        #   name: "ğŸŒ³ git Â· Protect main branches"
        #   args: [--branch, main, --branch, master, --branch, release/*]
      - id: check-added-large-files
        name: "ğŸŒ³ git Â· Block large file commits"
        args: [--maxkb=123]
        exclude: >
          (?x)^(
            .pnp.cjs|
            package-lock.json|
            npm-shrinkwrap.json|
            poetry.lock|
            Pipfile.lock|
            yarn.lock|
            sbom.json|
          )$
        # ----------------------------- ğŸ”’ Security Tools ---------------------------- #
      - id: detect-private-key
        name: "ğŸ”’ security Â· Detect private keys"

  - repo: https://github.com/pre-commit/pre-commit.git
    rev: v4.5.1
    hooks:
      - id: validate_manifest
        name: "ğŸ¤– manifest Â· Validate manifest scripts"

  - repo: https://github.com/doublify/pre-commit-hindent.git
    rev: b3680b6ebf9f7cf29b19307f246adef66756feef
    hooks:
      - id: hindent
        name: "ğŸ¤– hindent Â· Format scripts"

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v4.0.0
    hooks:
      - id: add-trailing-comma
        name: "ğŸ¤– comma Â· Add trailing comma"

    # --------------------------- ğŸ” Code Quality Tools -------------------------- #

    ### Python Tools ###
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        name: "ğŸ python Â· Py Upgrade"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.9
    hooks:
      - id: ruff-format
        name: "ğŸ python Â· Format with Ruff"

      - id: ruff
        name: "ğŸ python Â· Lint and perform unsafe auto-fixes with Ruff"
        args: [--unsafe-fixes]

      - id: ruff-check
        name: "ğŸ python Â· Check with Ruff"
        args: [--fix]

    # - repo: https://github.com/RobertCraigie/pyright-python
    #   rev: v1.1.406
    #   hooks:
    #     - id: pyright
    #       name: "ğŸ python Â· Check types"

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
        name: "ğŸ python Â· Validate pyproject.toml"
        additional_dependencies: ["validate-pyproject-schema-store[all]"]

    # ----------------------------- âš¡ï¸ uv Build Tools ---------------------------- #
    # This helps ensure cross-compatibility with people who don't wish to use uv
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.18
    hooks:
      - id: uv-sync
        name: "âš¡ï¸ uv Â· Sync dependencies with uv"
      - id: uv-lock
        name: "âš¡ï¸ uv Â· Update dependency lockfile"
      - id: uv-lock
        name: "âš¡ï¸ uv Â· Upgrade via uv sync --upgrade"
        alias: deps
        args: ["--upgrade"]
        stages: [manual]
      - id: uv-export
        name: "âš¡ï¸ uv Â· Export dependencies to requirements.txt"
        args:
          - "--no-dev"
          - "--no-emit-package"
          - ansible-core
          - "--no-emit-package"
          - resolvelib
          - "--no-emit-package"
          - ruamel-yaml-clib
          - "--no-emit-package"
          - tomli
          - "--no-emit-package"
          - typing-extensions
          - "--no-emit-project"
          - "--no-hashes"
          - "-o"
          - ".config/requirements-lock.txt"

    ### Shell ###
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      # Choose one of:
      # - id: shfmt         # native (requires Go to build)
      - id: shfmt-docker # Docker image (requires Docker to run)
        name: "ğŸš ğŸ³ shell Â· Format shell scripts"
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: v1.0.6
    hooks:
      - id: shell-lint
        name: "ğŸš shell Â· Lint shell scripts"
        args: [-x]
        exclude: >
          (?x)^(
            hooks|
            tests/.*|
            .envrc|
          )$

  - repo: https://github.com/openstack/bashate
    rev: 2.1.1
    hooks:
      - id: bashate
        name: "ğŸš shell Â· Check shell script code style"
        args: [-i, "E003,E006"]
        exclude: >
          (?x)^(
              trunk|
              scripts/run-python.sh|
              .envrc|
          )$

    ### Makefile ###
  - repo: https://github.com/mrtazz/checkmake.git
    rev: 0.2.2
    hooks:
      - id: checkmake
        name: "ğŸ® Makefile Â· Lint Makefile"

    ### SQL ###
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.5.0
    hooks:
      - id: sqlfluff-fix
        name: "ğŸ“Š SQL Â· Attempts to fix rule violations."
      - id: sqlfluff-lint
        name: "ğŸ“Š SQL Â· Lint SQL code files"

    ### Notebooks ###
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa
        entry: nbqa mdformat
        name: "ğŸ““ notebook Â· Format markdown cells"
        args: ["--nbqa-md"]
        types: [jupyter]
        additional_dependencies:
          - mdformat
          - mdformat-gfm
          - mdformat-ruff
          - mdformat-frontmatter
          - ruff
        # - id: nbqa-mypy
        #   name: "ğŸ““ notebook Â· Type-check cells"

    ### Markdown ###
    # mdformat --check README.md CHANGELOG.md
    # - repo: https://github.com/hukkin/mdformat
    #   rev: 1.0.0
    #   hooks:
    #     - id: mdformat
    #       name: "ğŸ“ markdown Â· Format markdown"
    #       additional_dependencies:
    #         - mdformat-gfm # GitHub-Flavored Markdown support
    #         - mdformat-ruff # Python code formatting
    #         - mdformat-frontmatter # YAML frontmatter support
    #         - ruff # Required for mdformat-ruff
    # NOK with ruby 3.4.7
    # gem install mdl
    # - repo: https://github.com/markdownlint/markdownlint
    #   rev: v0.15.0
    #   hooks:
    #     - id: markdownlint
    #       name: "ğŸ“ markdown Â· Lint markdown"
    #       exclude: >
    #         (?x)^(
    #             CHANGELOG.md|
    #             README.md|
    #         )$

    ### Javascript & Web Tools ###
  - repo: https://github.com/biomejs/pre-commit
    rev: "v2.3.9"
    hooks:
      - id: biome-check
        name: "ğŸŸ¨ javascript Â· Lint, format, and safe fixes with Biome"
        additional_dependencies: ["@biomejs/biome@1.9.4"]
        exclude: >
          (?x)^(
              trivy-sbom.json|
              my-app/public/.*|
          )$

  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: htmllint
        name: "ğŸ“ html Â· Lint html"
        args: [--config, .eslintrc.json]
        files: ^src/
      - id: htmlhint
        name: "ğŸ“ html Â· Hint html"
        args: [--config, .htmlhintrc]
      - id: markdown-toc
        name: "ğŸ“ markdown Â· Toc markdown"
        args: [--maxdepth, "3", -i]

    ### PNG Images ###
    # - repo: https://github.com/shssoichiro/oxipng
    #   rev: v9.1.5
    #   hooks:
    #     - id: oxipng
    #       name: "ğŸ–¼ï¸ images Â· Optimize PNG files"
    #       args: ["-o", "4", "--strip", "safe", "--alpha"]

    ### Additional File Types ###
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: "âœ¨ misc-files Â· Format misc web files"
        types_or: [yaml, html, scss]
        additional_dependencies:
          - prettier@3.4.2
        exclude: >
          (?x)^(
              trivy-sbom.json|
              my-app/public/.*|
          )$

    ### Data & Config Validation ###
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.36.0
    hooks:
      - id: check-github-workflows
        name: "ğŸ§© github-actions Â· Validate gh workflow files"
        args: ["--verbose"]
      - id: check-taskfile
        name: "âœ… taskfile Â· Validate Task configuration"

  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint-docker
        name: "ğŸ³ hadolint Â· Validate Dockerfile"

    # ----------------------------- ğŸ”’ Security Tools ---------------------------- #

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.2
    hooks:
      - id: bandit
        name: "ğŸ”’ security Â· Detect security issues"
        args: [-c, .bandit.yml]
        exclude: >
          (?x)^(
            noxfile.py|
            versioneer.py|
          )$

  - repo: https://github.com/IamTheFij/ansible-pre-commit
    rev: v1.0.1
    hooks:
      - id: encryption-check
        name: "ğŸ”’ security Â· Detect encryption"
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks-docker
        name: "ğŸ”’ ğŸ³ security Â· Detect hardcoded secrets"
        entry: zricethezav/gitleaks protect --verbose --redact --staged

    ### Ansible ###
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v25.12.1
    hooks:
      - id: ansible-lint
        name: "ğŸ“œ ansible - Lint Ansible"
        # args: [--verbose]
        files: \.(yaml|yml)$
        exclude: >
          (?x)^(
            .travis.yml|
            docker/|
            requirements.yml|
            playbooks/group_vars/all/vault.yml|
            .gitlab-ci.yml|
          )$
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        name: "ğŸ“œ yamllint - Lint Yaml"
        args: [--format, parsable, --strict]

    # ---------------------------------------------------------------------------- #
    #                            ğŸ“ Commit Message Hooks                           #
    # ---------------------------------------------------------------------------- #
    #
    # --------------------------- âœï¸ Git Commit Quality -------------------------- #

    ### Commit Message Standards ###
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.23.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          - "@commitlint/config-conventional"
          - conventional-changelog-conventionalcommits
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.10.1
    hooks:
      - id: commitizen
        name: "ğŸŒ³ git Â· Validate commit message"
        stages: [commit-msg]
        additional_dependencies: [cz-conventional-gitmoji]
      - id: commitizen-branch
        stages: [pre-push]

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        name: "ğŸŒ³ git Â· Lint"
      - id: gitlint-ci
        name: "ğŸŒ³ git Â· Lint in CI"
        args: [--debug, --commits, mybranch] # enable debug mode, lint all commits in mybranch


    # ---------------------------------------------------------------------------- #
    #                            ğŸ‘‘ Mega linter                                    #
    # ---------------------------------------------------------------------------- #

    # - repo: https://github.com/oxsecurity/megalinter
    #   rev: v9.0.1
    #   hooks:
    #     - id: megalinter-incremental  # Faster, less thorough
    #       name: "ğŸ‘‘ ğŸ³ megalinter - All in linter"
    #       stages:
    #         - pre-commit
    #       args:
    #         - mega-linter-runner
    #         - --containername
    #         - "megalinter-incremental"
    #         - --remove-container
    #         # - --fix
    #         # - --env
    #         # - "'APPLY_FIXES=all'"
    #         - --env
    #         - "'CLEAR_REPORT_FOLDER=true'"
    #         - --env
    #         - "'LOG_LEVEL=warning'"
    #         - --filesonly
    #         - --flavor
    #         - "python"
