---
# This playbook contains common plays that will be run on all nodes.

- name: workstation | Load main workstation tasks
  ansible.builtin.import_tasks: workstation.yml
  when: workstation_enabled
  tags: [workstation]
