---
# See https://www.linuxuprising.com/2020/05/how-to-install-pop-shell-tiling.html

# cdr
# sudo apt install node-typescript make git
#
# git clone https://github.com/pop-os/shell
# cd shell
# ./rebuild.sh
#
# sudo apt install cargo rustc libgtk-3-dev
# git clone https://github.com/pop-os/shell-shortcuts
# cd shell-shortcuts
# make
# sudo make install
